puts 'augusto'.object_id
puts 'augusto'.object_id
puts 'augusto'.object_id
puts 'augusto'.object_id
puts 'augusto'.object_id
puts '================'
puts :augusto.object_id
puts :augusto.object_id
puts :augusto.object_id
puts :augusto.object_id
puts :augusto.object_id
puts :augusto.object_id